
#HHS_PLOT_FUNS <- dput(ls("package:rarehhs", pattern = "plot_"))
# HHS_PLOT_FUNS <- c("clean_plot_data", "ggplot_add", "ggplot_build", "ggplot_gtable",
#                         "plot_horiz_bar", "plot_q08_religion", "plot_q09_region_member",
#                         "plot_q10_mpa_important", "plot_q11_income", "plot_q12_household_fishing",
#                         "plot_q13_processing", "plot_q14_responsibilities", "plot_q16_hh_main_fisher",
#                         "plot_q17_fishing_low_profit", "plot_q18_fishing_high_profit",
#                         "plot_q19_current_fish_catch", "plot_q20_gear", "plot_q22_catch_5yrs", "plot_q23_job_secure",
#                         "plot_q24_items_owned", "plot_q25_financial_account", "plot_q26_fishing_income_save",
#                         "plot_q27_emergency_funds", "plot_q28_buyer_loans", "plot_q29_family_income",
#                         "plot_q30a_trust_local_decision", "plot_q30b_trust_regional_decision",
#                         "plot_q30c_trust_community", "plot_q30d_trust_village_alert",
#                         "plot_q31_my_community_ability", "plot_q32_fishery_benefit_equal",
#                         "plot_q33_ma_familiar", "plot_q34_gear_restrictions", "plot_q36_fish_size_restriction",
#                         "plot_q37_ability_min_size", "plot_q38_reserve_fishing_allowed",
#                         "plot_q39_ma_boundaries_aware", "plot_q40_reserve_boundaries_aware",
#                         "plot_q41_ma_fishers_allowed", "plot_q42b_problem_restricted_gear",
#                         "plot_q42c_problem_undersize", "plot_q42d_problem_inside_reserve",
#                         "plot_q42e_problem_unauthorized", "plot_q43_ma_benefits", "plot_q44a_meeting_attendance",
#                         "plot_q44b_meeting_attendance_alt", "plot_q45_leadership_position",
#                         "plot_q46_represent_interests", "plot_q47_represent_contributions",
#                         "plot_q51_fishers_caught", "plot_q51_fishers_permission", "plot_q52_ma_benefit_5yrs",
#                         "plot_q53_encourage_regulations", "plot_q54_food_availability",
#                         "plot_q55_worry_food", "plot_q56_reduce_meal_size_adult", "plot_q59_food_procurement",
#                         "plot_q60_hh_fish_consumption", "plot_q61a_current_regulations",
#                         "plot_q61b_catch_recording", "plot_q61c_community_participation",
#                         "plot_q61d_strong_enforcement", "plot_q61e_rights_distribution_fair",
#                         "plot_q61f_fishing_change_behavior", "plot_q61g_individual_behavior",
#                         "plot_q61h_help_neighbors", "plot_q63_fishing_in_reserve", "plot_q64_wrong_fishing_reserve",
#                         "plot_q65_no_wrong_fishing_reserve", "plot_q66a_reaction_fishing_reserve",
#                         "plot_q66b_response_fishing_reserve", "plot_q67_reserve_boundry",
#                         "plot_q68_fish_sold", "plot_q70a_hh_income_all", "plot_q70b_hh_income_fishing",
#                         "plot_q72_current_economic", "plot_q77_hh_ends_meet", "plot_q78_financial_decisions",
#                         "prep_data_for_plot_facet")
HHS_PLOT_FUNS <- c(
  "plot_q21_current_fish_catch", "plot_q45_gear_restrictions", "plot_q47_ability_min_size",
  "plot_q48_reserve_fishing_allowed", "plot_q58_represent_role", "plot_q65_fishers_caught",
  "plot_q65_fishers_permission", "plot_q66_ma_benefit_5yrs", "plot_q74a_current_regulations",
  "plot_q74b_catch_recording", "plot_q74e_rights_distribution_fair"
)
NO_PLOT_ATTEMPT <- NULL
